## Snakemake configuration
## @Author Floris Barthel

## Full path to cluster settings
cluster_json:     "cluster.json"

## Temporary directory
tempdir:          "Temp"

## Reference genome
reference_fasta:  "data/ref/human_g1k_v37_decoy.fasta"

## Reference dictionary
reference_dict:   "data/ref/human_g1k_v37_decoy.dict"

## GATK options
seconds_between_progress_updates: 900

samtofastq_java_opt: "'-Dsamjdk.buffer_size=131072 -Dsamjdk.compression_level=1 -XX:GCTimeLimit=50 -XX:GCHeapFreeLimit=10 -Xmx128m'"
mergebamalignment_java_opt: "'-Dsamjdk.buffer_size=131072 -Dsamjdk.use_async_io=true -Dsamjdk.compression_level=1 -XX:+UseStringCache -XX:GCTimeLimit=50 -XX:GCHeapFreeLimit=10 -Xmx5000m'"

## END #
